apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: openshift/postgresql-92-centos7
    importPolicy: {}
    name: latest
    referencePolicy:
      type: ""
