apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: teamdojo
  name: teamdojo-int
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: "teamdojo:develop"
    generation: null
    importPolicy: {}
    name: develop
    referencePolicy:
      type: Source
