apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: teamdojo
  name: teamdojo
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: "teamdojo:latest"
    generation: null
    importPolicy:
      scheduled: true
    name: latest
    referencePolicy:
      type: Source
  - from:
        kind: DockerImage
        name: "teamdojo:develop"
    generation: null
    importPolicy:
      scheduled: true
    name: develop
    referencePolicy:
      type: Source
