apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: teamdojo-int
  name: teamdojo-int
spec:
  replicas: 1
  selector:
    app: teamdojo-int
    deploymentconfig: teamdojo-int
  template:
    metadata:
      labels:
        app: teamdojo-int
        deploymentconfig: teamdojo-int
    spec:
      containers:
      - image: teamdojo
        name: teamdojo
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod,swagger"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://postgres-int:5432/dojo"
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: slabdojo-db
                key: user
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: slabdojo-db
                key: password
          - name: JHIPSTER_SLEEP
            value: "10" # gives time for the database to boot before the application
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - teamdojo
      from:
        kind: ImageStreamTag
        name: teamdojo:latest
    type: ImageChange
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: teamdojo-int
  name: teamdojo-int
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: teamdojo-int
