apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: teamdojo-int
  name: teamdojo-int
spec:
  replicas: 1
  selector:
    app: teamdojo-int
    deploymentconfig: teamdojo-int
  template:
    metadata:
      labels:
        app: teamdojo-int
        deploymentconfig: teamdojo-int
    spec:
      containers:
      - image: teamdojo
        name: teamdojo
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod,swagger"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://postgres-int:5432/teamdojo"
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: slabdojo-db
                key: user
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: slabdojo-db
                key: password
          - name: JHIPSTER_SLEEP
            value: "10" # gives time for the database to boot before the application
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - teamdojo
      from:
        kind: ImageStreamTag
        name: teamdojo:latest
    type: ImageChange
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: teamdojo-int
  name: teamdojo-int
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: teamdojo-int
    deploymentconfig: teamdojo-int
---
apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: openshift/postgresql-92-centos7
    importPolicy: {}
    name: latest
    referencePolicy:
      type: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres-int
  name: pg-data-int
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: postgres-int
  name: postgres-int
spec:
  replicas: 1
  selector:
    app: postgres-int
    deploymentconfig: postgres-int
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        app: postgres-int
        deploymentconfig: postgres-int
    spec:
      containers:
      - image: postgres
        name: postgres
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRESQL_DATABASE
          value: teamdojo
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: slabdojo-db
              key: user
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: slabdojo-db
              key: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pg-data
      volumes:
      - name: pg-data
        persistentVolumeClaim:
          claimName: pg-data-int
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - postgres
      from:
        kind: ImageStreamTag
        name: postgres:latest
    type: ImageChange
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-int
  name: postgres-int
spec:
  ports:
  - name: postgres-int
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-int
    deploymentconfig: postgres-int
