apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: openshift/postgresql-92-centos7
    importPolicy: {}
    name: latest
    referencePolicy:
      type: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres
  name: pg-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    app: postgres
    deploymentconfig: postgres
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        app: postgres
        deploymentconfig: postgres
    spec:
      containers:
      - image: postgres
        name: postgres
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRESQL_DATABASE
          value: teamdojo
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: slabdojo-db
              key: user
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: slabdojo-db
              key: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pg-data
      volumes:
      - name: pg-data
        persistentVolumeClaim:
          claimName: pg-data
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - postgres
      from:
        kind: ImageStreamTag
        name: postgres:latest
    type: ImageChange

